"""empty message

Revision ID: 835947b7b804
Revises: 0b543ef3d481
Create Date: 2024-08-06 21:04:56.195166

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '835947b7b804'
down_revision: Union[str, None] = '0b543ef3d481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column(
            'is_active', sa.Boolean(),
            nullable=False, server_default='true'
        )
    )
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
