version: "3.9"

services:
  db:
    image: postgres:16.3
    env_file: .env
    volumes:
      - db_prod:/var/lib/postgresql/data

  web:
    build:
      dockerfile: Dockerfile
    env_file: .env

volumes:
  db_prod:
