version: "3.9"

services:
  db:
    image: postgres:16.3
    env_file: env.example
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      dockerfile: Dockerfile-dev
    env_file: env.example
    ports:
      - "8000:8000"

volumes:
  db:
