version: "3.9"

services:
  db:
    image: postgres:16.3
    env_file: .env
    volumes:
      - db_prod:/var/lib/postgresql/data

  migration:
    build:
      dockerfile: Dockerfile
    env_file: .env
    command: uv run alembic upgrade head

  web:
    build:
      dockerfile: Dockerfile
    env_file: .env

  nginx:
    image: nginx:1.27.2
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "8000:80"

volumes:
  db_prod:
