"""empty message

Revision ID: 4178e1093776
Revises: 411f1c1654ea
Create Date: 2024-08-24 21:31:14.259898

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4178e1093776'
down_revision: Union[str, None] = '411f1c1654ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'refresh_tokens_user_id_fkey',
        'refresh_tokens',
        type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'refresh_tokens', 'users', ['user_id'],
        ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(
        'refresh_tokens_user_id_fkey',
        'refresh_tokens',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
